[tool.uv.workspace]
members = ["backend"]

[project]
name = "ko-merge"
version = "2.0.0"
description = "Ko-Merge application with FastAPI backend and React frontend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
dev-dependencies = []
